name: Build and Push Images

on:
  # Allows other workflows (e.g., tag-release.yml) to call this workflow and pass a version
  workflow_call:
    inputs:
      version:
        description: Version tag (e.g., v1.2.3)
        required: true
        type: string
  # Enables manual triggering from the GitHub Actions UI with a version input
  workflow_dispatch:
    inputs:
      version:
        description: Version tag (e.g., v1.2.3)
        required: true
        type: string

permissions:
  contents: read    # read repository content
  packages: write   # push images to GHCR

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      VERSION_TAG: ${{ inputs.version != '' && inputs.version || github.event.inputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        run: echo "$GITHUB_TOKEN" | docker login ghcr.io -u "${GITHUB_ACTOR}" --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync VERSION file with tag
        run: |
          TAG="${VERSION_TAG}"
          CLEAN_TAG="${TAG#v}"
          echo "${CLEAN_TAG}" > VERSION
          echo "Using VERSION=$(cat VERSION) (from tag ${TAG})"

      - name: Build and push images via Makefile
        run: make all
